config/routes.rb
Rails.application.routes.draw do
  
  
  
  resources :permissions_roles
  resources :permissions
  resources :roles
  get 'request_masters_admin' => "request_masters#request_masters_admin", as: :request_masters_admin
  get 'payment_tables_admin' => "payment_tables#payment_tables_admin", as: :payment_tables_admin
  get 'investment_masters_admin' => "investment_masters#investment_masters_admin", as: :investment_masters_admin

  
  post 'amfp_callback' => "callbacks#amfp_callback", as: :amfp_callback
  
  authenticated :user do
    root :to => 'home#dashboard', as: :authenticated_root
  end

  root :to => 'home#index'

  devise_scope :user do
     get "/login", :to => "devise/sessions#new", as: :login # Add a custom sign in route for user sign in
     delete "/logout", :to => "devise/sessions#destroy" # Add a custom sing out route for user sign out
     get "/register", :to => "devise/registrations#new", as: :register # Add a Custom Route for Registrations
  end
  
  devise_for :users
  resources :request_masters
  resources :payment_tables
  resources :referals_masters
  resources :investment_masters
  resources :account_masters
  resources :system_configs
end

app/models/permissions_role.rb
class PermissionsRole < ActiveRecord::Base
end

app/controllers/permissions_roles_controller.rb
class PermissionsRolesController < ApplicationController
  before_action :set_permissions_role, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  before_filter :load_permissions

  # GET /permissions_roles
  # GET /permissions_roles.json
  def index
    @permissions_roles = PermissionsRole.all
  end

  # GET /permissions_roles/1
  # GET /permissions_roles/1.json
  def show
  end

  # GET /permissions_roles/new
  def new
    @permissions_role = PermissionsRole.new
  end

  # GET /permissions_roles/1/edit
  def edit
  end

  # POST /permissions_roles
  # POST /permissions_roles.json
  def create
    @permissions_role = PermissionsRole.new(permissions_role_params)

    respond_to do |format|
      if @permissions_role.save
        format.html { redirect_to @permissions_role, notice: 'Permissions role was successfully created.' }
        format.json { render :show, status: :created, location: @permissions_role }
      else
        format.html { render :new }
        format.json { render json: @permissions_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permissions_roles/1
  # PATCH/PUT /permissions_roles/1.json
  def update
    respond_to do |format|
      if @permissions_role.update(permissions_role_params)
        format.html { redirect_to @permissions_role, notice: 'Permissions role was successfully updated.' }
        format.json { render :show, status: :ok, location: @permissions_role }
      else
        format.html { render :edit }
        format.json { render json: @permissions_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions_roles/1
  # DELETE /permissions_roles/1.json
  def destroy
    @permissions_role.destroy
    respond_to do |format|
      format.html { redirect_to permissions_roles_url, notice: 'Permissions role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permissions_role
      @permissions_role = PermissionsRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permissions_role_params
      params.require(:permissions_role).permit(:permission_id, :role_id)
    end
end

app/helpers/permissions_roles_helper.rb
module PermissionsRolesHelper
end

app/views/permissions_roles/_form.html.erb
<%= simple_form_for(@permissions_role) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :permission_id %>
    <%= f.input :role_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/permissions_roles/edit.html.erb
<h1>Editing Permissions Role</h1>

<%= render 'form' %>

<%= link_to 'Show', @permissions_role %> |
<%= link_to 'Back', permissions_roles_path %>

app/views/permissions_roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Permissions Roles</h1>

<table>
  <thead>
    <tr>
      <th>Permission</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permissions_roles.each do |permissions_role| %>
      <tr>
        <td><%= permissions_role.permission_id %></td>
        <td><%= permissions_role.role_id %></td>
        <td><%= link_to 'Show', permissions_role %></td>
        <td><%= link_to 'Edit', edit_permissions_role_path(permissions_role) %></td>
        <td><%= link_to 'Destroy', permissions_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permissions role', new_permissions_role_path %>

app/views/permissions_roles/new.html.erb
<h1>New Permissions Role</h1>

<%= render 'form' %>

<%= link_to 'Back', permissions_roles_path %>

app/views/permissions_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Permission:</strong>
  <%= @permissions_role.permission_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @permissions_role.role_id %>
</p>

<%= link_to 'Edit', edit_permissions_role_path(@permissions_role) %> |
<%= link_to 'Back', permissions_roles_path %>