config/routes.rb
Rails.application.routes.draw do
  
  
  
  resources :permissions_roles
  resources :permissions
  resources :roles
  get 'request_masters_admin' => "request_masters#request_masters_admin", as: :request_masters_admin
  get 'payment_tables_admin' => "payment_tables#payment_tables_admin", as: :payment_tables_admin
  get 'investment_masters_admin' => "investment_masters#investment_masters_admin", as: :investment_masters_admin

  
  post 'amfp_callback' => "callbacks#amfp_callback", as: :amfp_callback
  
  authenticated :user do
    root :to => 'home#dashboard', as: :authenticated_root
  end

  root :to => 'home#index'

  devise_scope :user do
     get "/login", :to => "devise/sessions#new", as: :login # Add a custom sign in route for user sign in
     delete "/logout", :to => "devise/sessions#destroy" # Add a custom sing out route for user sign out
     get "/register", :to => "devise/registrations#new", as: :register # Add a Custom Route for Registrations
  end
  
  devise_for :users
  resources :request_masters
  resources :payment_tables
  resources :referals_masters
  resources :investment_masters
  resources :account_masters
  resources :system_configs
end

app/models/account_master.rb
class AccountMaster < ActiveRecord::Base
end

app/controllers/account_masters_controller.rb
class AccountMastersController < ApplicationController
  before_action :set_account_master, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  before_filter :load_permissions

  # GET /account_masters
  # GET /account_masters.json
  def index
    @account_masters = AccountMaster.where(user_id: current_user.id)
  end

  # GET /account_masters/1
  # GET /account_masters/1.json
  def show
  end

  # GET /account_masters/new
  def new
    @account_master = AccountMaster.new
  end

  # GET /account_masters/1/edit
  def edit
  end

  # POST /account_masters
  # POST /account_masters.json
  def create
    @account_master = AccountMaster.new(account_master_params)

    respond_to do |format|
      if @account_master.save
        format.html { redirect_to @account_master, notice: 'Account master was successfully created.' }
        format.json { render :show, status: :created, location: @account_master }
      else
        format.html { render :new }
        format.json { render json: @account_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_masters/1
  # PATCH/PUT /account_masters/1.json
  def update
    respond_to do |format|
      if @account_master.update(account_master_params)
        format.html { redirect_to @account_master, notice: 'Account master was successfully updated.' }
        format.json { render :show, status: :ok, location: @account_master }
      else
        format.html { render :edit }
        format.json { render json: @account_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_masters/1
  # DELETE /account_masters/1.json
  def destroy
    @account_master.destroy
    respond_to do |format|
      format.html { redirect_to account_masters_url, notice: 'Account master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_master
      @account_master = AccountMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_master_params
      params.require(:account_master).permit(:user_id, :avaliable_balance, :status)
    end
end

app/helpers/account_masters_helper.rb
module AccountMastersHelper
end

app/views/account_masters/_form.html.erb
<%= simple_form_for(@account_master) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :avaliable_balance %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/account_masters/edit.html.erb
<h1>Editing Account Master</h1>

<%= render 'form' %>

<%= link_to 'Show', @account_master %> |
<%= link_to 'Back', account_masters_path %>

app/views/account_masters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Account Masters</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Avaliable balance</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_masters.each do |account_master| %>
      <tr>
        <td><%= account_master.user_id %></td>
        <td><%= account_master.avaliable_balance %></td>
        <td><%= account_master.status %></td>
        <td><%= link_to 'Show', account_master %></td>
        <td><%= link_to 'Edit', edit_account_master_path(account_master) %></td>
        <td><%= link_to 'Destroy', account_master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account master', new_account_master_path %>

app/views/account_masters/new.html.erb
<h1>New Account Master</h1>

<%= render 'form' %>

<%= link_to 'Back', account_masters_path %>

app/views/account_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @account_master.user_id %>
</p>

<p>
  <strong>Avaliable balance:</strong>
  <%= @account_master.avaliable_balance %>
</p>

<p>
  <strong>Status:</strong>
  <%= @account_master.status %>
</p>

<%= link_to 'Edit', edit_account_master_path(@account_master) %> |
<%= link_to 'Back', account_masters_path %>